Update Old Pages/Printers.md
StarLegacy/StarLegacy.Wiki pull request #41
Opened 2018-11-01 22:53 UTC by Shady9879

Added pictures and text formatting. Merged the carbon processor to this page.

2018-11-01 23:45 UTC, hafarooki requested changes
Looks like you forgot to actually delete the processors page

2018-11-01 23:50 UTC, hafarooki requested changes
Formatting on this one isn't very good, try to make it a bit more consistent and use markdown features properly

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +# Printers and Processors
```suggestion
# Printers
```

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +- Concrete powder, glass, sponge, and terracotta.
```suggestion
```

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +*Carbon processors* simply process raw concrete powder into concrete.
move this to the carbon printer section

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +## Printers
```suggestion
```

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +### Using a printer:
```suggestion
## Using a printer:
```

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +### Printer Multiblock:
```suggestion
## Printer Multiblock
```

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +- NOTE: Copper blocks are only on the LEFT of the sign with [Printer] on it.
```suggestion
> Copper blocks are only on the LEFT of the sign with [Printer] on it.
```

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +*Universal Printer Materials List:*
```suggestion
### Shared required materials
```

2018-11-01 23:50 UTC, Miclebrick commented on Old Pages/Printers.md
> +### **Carbon Printer**
```suggestion
### Carbon Printer
```

2018-11-03 21:27 UTC, Shady9879 commented
Made changes, for whatever reason I don't see the carbon processor page in my file repository?

2018-11-04 00:05 UTC, Miclebrick commented
IDK :P

2018-11-04 00:07 UTC, hafarooki requested changes

2018-11-04 00:07 UTC, Miclebrick commented on Old Pages/Printers.md
> +## Printer Multiblock:
Remove colon

2018-11-04 00:07 UTC, Miclebrick commented on Old Pages/Printers.md
> +- Red blocks are replaced with the "machinery blocks".
Maybe use bold rather than quote

2018-11-14 19:59 UTC, Shady9879 commented
Deleted and re downloaded and still don't see the carbon processor page.. If you still see it maybe you can delete that one please.

2018-11-14 19:59 UTC, closed without merging

2018-11-14 20:00 UTC, Miclebrick commented
Did you close it without merging?